language: node_js
node: 14

notifications:
  email: false

services:
  - mongodb
  - redis

jobs:
  include:
    - name: apollo-bundle
      cache: npm
      env: TARGET=projects/apollo-bundle
    - name: apollo-security-bundle
      cache: npm
      env: TARGET=projects/apollo-security-bundle
    - name: core
      cache: npm
      env: TARGET=projects/core
    - name: ejson
      cache: npm
      env: TARGET=projects/ejson
    - name: email-bundle
      cache: npm
      env: TARGET=projects/email-bundle
    - name: graphql-bundle
      cache: npm
      env: TARGET=projects/graphql-bundle
    - name: http-bundle
      cache: npm
      env: TARGET=projects/http-bundle
    - name: logger-bundle
      cache: npm
      env: TARGET=projects/logger-bundle
    - name: mikroorm-bundle
      cache: npm
      env: TARGET=projects/mikroorm-bundle
    - name: mongo-bundle
      cache: npm
      env: TARGET=projects/mongo-bundle
    - name: nova
      cache: npm
      env: TARGET=projects/nova
    - name: password-bundle
      cache: npm
      env: TARGET=projects/password-bundle
    - name: rabbitmq-bundle
      cache: npm
      env: TARGET=projects/rabbitmq-bundle
    - name: security-bundle
      cache: npm
      env: TARGET=projects/security-bundle
    - name: security-mongo-bundle
      cache: npm
      env: TARGET=projects/security-mongo-bundle
    - name: smart
      cache: npm
      env: TARGET=projects/smart
    - name: terminal-bundle
      cache: npm
      env: TARGET=projects/terminal-bundle
    - name: ui-apollo-bundle
      cache: npm
      env: TARGET=projects/ui-apollo-bundle
    - name: validator-bundle
      cache: npm
      env: TARGET=projects/validator-bundle
    - name: x
      cache: npm
      env: TARGET=projects/x
    - name: x-bundle
      cache: npm
      env: TARGET=projects/x-bundle
    - name: x-cron-bundle
      cache: npm
      env: TARGET=projects/x-cron-bundle
    - name: x-password-bundle
      cache: npm
      env: TARGET=projects/x-password-bundle
    - name: x-s3-bundle
      cache: npm
      env: TARGET=projects/x-s3-bundle
    - name: x-ui
      cache: npm
      env: TARGET=projects/x-ui
    - name: x-ui-admin
      cache: npm
      env: TARGET=projects/x-ui-admin
    - name: x-ui-collections-bundle
      cache: npm
      env: TARGET=projects/x-ui-collections-bundle
    - name: x-ui-guardian-bundle
      cache: npm
      env: TARGET=projects/x-ui-guardian-bundle
    - name: x-ui-i18n-bundle
      cache: npm
      env: TARGET=projects/x-ui-i18n-bundle
    - name: x-ui-next
      cache: npm
      env: TARGET=projects/x-ui-next
    - name: x-ui-react-bundle
      cache: npm
      env: TARGET=projects/x-ui-react-bundle
    - name: x-ui-react-router-bundle
      cache: npm
      env: TARGET=projects/x-ui-react-router-bundle
    - name: x-ui-router
      cache: npm
      env: TARGET=projects/x-ui-router
    - name: x-ui-session-bundle
      cache: npm
      env: TARGET=projects/x-ui-session-bundle
script: cd $TARGET && npm install && npm run test
# script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && npm install && npm run test; else echo "$TARGET is NOT being built"; fi
